### ISSUE TITLE
Wrong props when nesting components

### ISSUE THREAD

**Issue by manuelmoritz1308** [rofrischmann/react-look#253] opened 2016-04-08 08:50 UTC
**Version**: 1.0.0 (beta8)
**Environment**: React
**Type**: Bug/Question

-------------------
#### Description
Hi,
I've just started using this great library so maybe my problem is not a bug, but at the moment I don't think that the behavior works as designed.

I have a component with the following render method.

```javascript
// imports...

const Page = ({ children }) => (
  <Container>
    <Span span={10} pre={1} post={1}>
      <div className={styles.spacer}>
        {children}
      </div>
    </Span>
  </Container>
);

const styles = StyleSheet.create({
  spacer: {
    padding: '40px 20px',
    marginBottom: 60,
    'pullUp=true': {
      marginTop: -130,
    },
  },
});

Page.propTypes = {
  pullUp: PropTypes.bool,
};

export default look(Page);
```

The `<Span>` component itself is a look enabled component with stateful behavior. The `<Page>` component should have stateful selector, too. But it turns out, that the defined rules are not working.
I added a stateful value and logged the props. Instead of the props that get passed to the `<Page>` component the function receives the props from the `<Span>` component.

Is there any way to get this working at the moment or am I missing something?

Thank you
Manuel

**Comment by rofrischmann** [comment] 2016-04-08 08:59
Hey,
Look enhanced Components always resolve themselve using their own props, that's why your `<Span>` Component uses all the props passed to your `<Span>` to resolve stateful styles.

If you want to use your `<Page>` props within `<Span>` you either have to pass them manually or use React's `context` to achieve the same effect without having to pass all the props down the line.

**Comment by manuelmoritz1308** [comment] 2016-04-08 09:11
Thanks for your answer.

I don't know if I explained it well enough, the problem is this:

There is the `<Page>` component which is Look enhanced. (see the div that wraps the children)
Then there is a stateful selector (`'pullUp=true'`) which should control the classes on the div when the `<Page>` component receives the `pullUp` prop. This works when I remove the `<Span>` component. This doesn't work with the `<Span>` component wrapping the div because the styles are now resolved using the `<Span>`'s props (`span`, `pre`, `post`). The `<Span>` component is Look enhanced as well.

Isn't this a bug? I don't want to use any parent props inside a child component, I just want to use the props on the current component inside the `StyleSheet.create()` function regardless of the structure inside this component.

**Comment by rofrischmann** [comment] 2016-04-08 09:18
Ah I see. Now I get what the problem is, sorry. I am aware that you consider this a bug while still I think there's nothing we can do to it actually (at least not without huge performance loss).

React itself will automatically trigger rerendering of every custom Component inside the changed one. This means rerendering `<Page>` automatically leads to rerendering `<Span>` and as your `div` is inside the `<Span>` it is considered its child. Even if we render all `<Page>` children with the correct props, we still need to render the `<Span>` again itself (otherwise you might get wrong output). This also leads to resolving all the stuff inside `<Span>` which would finally change our `div` again.

After all we would have rendered the `div` twice and still remain with the *wrong* output. That's why Look automatically stops child resolving if it iterates another Look-enhanced Component. (as those get resolved anyway).

**Comment by manuelmoritz1308** [comment] 2016-04-08 09:28
Okay,
if it's not a bug that's fine with me, but I don't quite get the reason for this behavior. I thought the look enhancer would tie the styles in the wrapped/enhanced component to the component's props/state. Doesn't the div somehow "belong" to the '<Page>' component?

Anyway, if you are sure this is not a bug or should somehow be changed feel free to close the issue.
Thanks for the fast response. (It helps that you also live in Germany :D )

**Comment by rofrischmann** [comment] 2016-04-08 09:34
Hehe yeah, it's quite rare to find people within the same timezone :D 
Well yeah, I'd call it a bug with no fixing solution (at least right now).

The problem is that React treats nested elements (Components and pure HTML tags) as children of the upper Component which makes your `div` belonging to `<Span>` instead of `<Page>`. As far as I know there's nothing I can do about this right now. 
Correct me if anythings wrong here, I am not a React core expert :P

**Comment by rofrischmann** [comment] 2016-04-11 09:40
@manuelmoritz1308 Would you mind if I close this issue for now? As far as I see we will not have a solution for this soon..

**Comment by manuelmoritz1308** [comment] 2016-04-11 12:44
@rofrischmann Of course you can close this as I haven't a solution to this problem, either. Thanks for your help and the great package! We will definitely use this at our internal projects at Bitmade. So maybe I will come up with some ideas or bugs in the future 😄

**Closed** 2016-04-13 12:30 UTC
