### ISSUE TITLE
New class added instead of old one being replaced

### ISSUE THREAD

**Issue by wagerfield** [rofrischmann/react-look#279] opened 2016-05-02 12:32 UTC
**Version**: 1.0.0-beta8
**Environment**: React, React DOM, Webpack
**Build Tools**: `webpack@1.12.15`, `react-hot-loader@1.3`, `babel-loader@6.2.4`
**Type**: Bug

-------------------
#### Description

When using hot reloading / module replacement, new classes are added to `_react-look-stylesheet` that override old ones rather than replacing them. This happens every time a file containing `StyleSheet.create({ ... })` changes.

Since the order of classes in a `<style/>` block matter—whereby the last ones to appear overrides any preceding ones, this leads to undesired and incorrect behaviour.

Refreshing the page results in the correct and expected class order, but hot reloading creates new classes that invalidate the correct class order.

-------------------
#### Steps to Reproduce

For this explanation, let's assume I have a project directory structure like this:
```
- components
  - message
    - MessageComponent.js
    - MessageComponentStyles.js
- styles
  - BaseStyles.js
```

Where `BaseStyles.js` looks like this:
```
// styles/BaseStyles.js
import { StyleSheet } from 'react-look';
export default StyleSheet.create({
  background: {
    backgroundColor: 'blue'
  }
});
```

...and `MessageComponentStyles.js` and `MessageComponent.js` look like this:
```
// components/message/MessageComponentStyles.js
import { StyleSheet } from 'react-look';
export default StyleSheet.create({
  component: {
    backgroundColor: 'red'
  }
});

// components/message/MessageComponent.js
import React from 'react';
import look, { StyleSheet } from 'react-look';
import BaseStyles from '../../styles/BaseStyles';
import ComponentStyles from './MessageComponentStyles';
export default look(React.createClass({
  render() {
    const styles = StyleSheet.combineStyles(
      BaseStyles.background,
      ComponentStyles.component
    );
    return (<div className={styles}>Some Message</div>);
  }
});
```

...`react` and `react-look` would render something like this to the DOM:
```
<div className="c1 c2">Some Message</div>
```

The `backgroundColor` of the `<div>` would be `red` since `ComponentStyles.component` is added after `BaseStyles.background` in the call to `StyleSheet.combineStyles()`—as you would expect.

However, with hot reloading if I then change `BaseStyles.js` so that `backgroundColor` is set to `orange` like so:
```
// styles/BaseStyles.js
import { StyleSheet } from 'react-look';
export default StyleSheet.create({
  background: {
    backgroundColor: 'orange'
  }
});
```

`react-look` creates a new class, `react` calls the `render` method again and we would see something like this to the DOM:
```
<div className="c3 c2">Some Message</div>
```

`c3` is the new class that has been created and appears _after_ `c2` in `_react-look-stylesheet` and thus overrides it. This is obviously not what is desired nor expected. As I mentioned above, refreshing the page fixes this problem, since `c3` then becomes `c1` again.

**Comment by rofrischmann** [comment] 2016-05-05 15:55
@wagerfield I understand the problem you're having right now, but I am unsure if this really is an issue of Look. It is not said to support any kind of Hot Reloading and unfortunately it even does, but not with your code structure. I am not sure how to "solve" the problem within Look as you're storing your basic styles within another file which will lead to a new className if it is reloaded.

If you got any idea on how to solve this problem in general feel free to tell me right away, but I think that Hot Reloading still is a very experimental technique and the issue is a side-effect which you either need to "fix" by reloading the whole page or by changing your project architecture to store all Component related styles within one file.
e.g. you could keep your BaseStyles as a pure Object and call `StyleSheet.create()` within your MessageComponent itself.

**Comment by wagerfield** [comment] 2016-05-05 16:08
Thanks @rofrischmann I appreciate you taking the time to look at this.

That's not too bad an idea having my `BaseStyles` and other such reusable style chunks stored as pure objects. I will take your advice and do that.

Would be nice to get this working with Hot Reloading, but like you, I don't really have time to take a look into a solution right now.

I'll leave this issue open, but please feel free to close if you don't think it's within the scope of React Look.

Thanks again 🎈

**Comment by rofrischmann** [comment] 2016-05-05 16:13
Yeah, I'd also like to have a solid hot reloading support, but still I am not sure if this is something we can cover just within Look. Perhaps it will get solved automatically as soon as I improved the rendering mechanism overall, but I am not sure with this. 

I guess for now its a good solution to just store those reusable styles as pure objects or (if you want to prevent multiple classes with the same styles assigned) just do the manual reloading if you change the basic styles.
I will try to take this in consideration if I finally have more time again after exams. And thanks for reporting :)

**Comment by rofrischmann** [comment] 2016-06-19 11:22
I will for now close this one as I was not able to get hot reloading do the trick without any major change, might reopen if the HMR situations changes sometime

**Closed by rofrischmann** 2016-06-19 11:22 UTC
