### ISSUE TITLE
"SASS-like Nesting" - Unable to Style Through Inheritance

### ISSUE THREAD

**Issue by joncursi** [rofrischmann/react-look#281] opened 2016-05-05 21:08 UTC
The introductory guide for `react-look` says that this project supports SASS-like nesting of CSS elements, but my findings are of the contrary. Example attempting to use BEM with some simple CSS inheritance:

Desired HTML:

```
...
<a class="drawer__link drawer__link--active">
  <div>Please style me through inheritance</div>
</a>
...

```

JSX:

```jsx
<Link
  className={styles.drawer__link}
  activeClassName={styles['drawer__link--active']}
  to="/"
>
...
</Link>
```

Styles:

```jsx
const styles = StyleSheet.create({
...
  drawer__link: {
    textDecoration: 'none',
  },
  'drawer__link--active': {
    '> div': {                    // this doesn't work!
      backgroundColor: 'rgba(0, 0, 0, .03)',
    },
  },
...

**Comment by rofrischmann** [comment] 2016-05-05 21:28
Uhm. The Sass-like Syntax was supposed only to tell you're able to nest pseudo classes within style objects. Look actually doesn't support CSS selectors like `>` by design. 
You still could simply build a plugin for this, I could do it next week if you want to, but I guess that's not what Look was build for.
Look more or less forces you to get rid of all those conditional CSS selectors such as `>`, `~` or `+`. It is purely class-based and styles are defined on a tag/element-base rather to remove complexity and specificity problems of CSS.

While it transforms to CSS this does not mean you actually "write" CSS. Hope this clears some of the core ideas and somehow answers your question if not with a nice solution.
Feel free to tell your specific use-case and I am sure to have an elegant way to do it with Look too :)

**Comment by joncursi** [comment] 2016-05-05 21:53
Ah okay. The issue I have is that I'm using [Material UI](https://github.com/callemall/material-ui) to pull in components through NPM, so I don't necessarily have "control" over that `<div>` I'm trying to style in the example above - that is bundled within an imported component from NPM. So I can't attach styles to it myself, so I _need_ some sort of CSS inheritance to get styles to it.

**Comment by rofrischmann** [comment] 2016-05-06 01:03
Ah I see, that really is a problem sometimes :/
One way to do this is the following:
```javascript
const styles = StyleSheet.create({
  'drawer__link--active': {/* some styles if at all */}
})

StyleSheet.addCSS({
  [styles[ 'drawer__link--active'] + '  > div'] : {
    backgroundColor: 'rgba(0, 0, 0, .03)'
  }
})
```

`StyleSheet.addCSS` was made especially to paste legacy CSS (you can also insert actual CSS files with a CSS loader as it is provided e.g. by Webpack) or to define global CSS in general e.g. html, body styles or general basic styles for whole tags.

**Comment by rofrischmann** [comment] 2016-05-07 21:57
I will close this as there is a way to solve it as showed above. I'll be more than happy to present a better way soon, as I found one, but it is not compatible with the current render mechanism.

**Closed by rofrischmann** 2016-05-07 21:57 UTC
